import type { AutomationActionKind, AutomationTriggerKind, CalendarTone } from "@/lib/types/domain";
import type { UnifiedEvent } from "@/lib/repositories/calendar.repository";

export const weekdays = ["DOM", "SEG", "TER", "QUA", "QUI", "SEX", "SAB"];

export const toneStyle: Record<CalendarTone, string> = {
  task: "bg-primary/25 text-foreground",
  meeting: "bg-sky-500/22 text-foreground",
  payment: "bg-primary/35 text-foreground shadow-glow-sm",
  board: "bg-indigo-400/20 text-foreground",
  visit: "bg-emerald-500/20 text-foreground",
};

export const sourceLabel: Record<UnifiedEvent["source"], string> = {
  manual: "Manual",
  visit: "Visita",
  charge: "Cobranca",
  contract: "Contrato",
  meeting: "Assembleia",
  automation: "Automacao",
};

export const triggerOptions: Array<{ value: AutomationTriggerKind; label: string; hint: string }> = [
  { value: "once", label: "Uma vez", hint: "Executa em uma data e hora específicas." },
  { value: "daily", label: "Diária", hint: "Executa todos os dias no horário escolhido." },
  { value: "weekly", label: "Semanal", hint: "Executa nos dias da semana selecionados." },
  { value: "monthly", label: "Mensal", hint: "Executa em dias específicos do mês." },
  { value: "interval_days", label: "Intervalo", hint: "Executa a cada N dias." },
  { value: "charge_due", label: "Vencimento", hint: "Executa relativo ao vencimento de cobranças." },
];

export const actionOptions: Array<{ value: AutomationActionKind; label: string; group: string; example: Record<string, unknown>; target?: boolean }> = [
  { value: "create_client", label: "Criar cliente", group: "Clientes", example: { kind: "pf", name: "", phone: "", whatsapp: null, email: null, document: null, address: null, rolesInBusiness: ["lead"], tags: [] } },
  { value: "update_client", label: "Editar cliente", group: "Clientes", target: true, example: { tags: ["automacao"] } },
  { value: "create_property", label: "Criar imovel", group: "Imoveis", example: { kind: "apartamento", address: "Endereco", status: "disponivel", availability: "ambos", photos: [] } },
  { value: "update_property", label: "Editar imovel", group: "Imoveis", target: true, example: { status: "disponivel" } },
  { value: "create_charge_standalone", label: "Criar boleto/PIX para cliente", group: "Financeiro", example: { clientId: "", amount: 100, dueDate: "2026-07-10", method: "boleto", description: "Cobranca avulsa" } },
  { value: "create_charge_and_send_whatsapp", label: "Criar boleto e enviar WhatsApp", group: "Financeiro", example: { clientId: "", amount: 100, dueDate: "2026-07-10", method: "boleto", description: "Cobranca avulsa" } },
  { value: "create_charge_for_installment", label: "Emitir cobranca de parcela", group: "Financeiro", example: { sourceId: "", method: "boleto" } },
  { value: "create_charge_for_condo_fee", label: "Emitir cobranca condominio", group: "Financeiro", example: { sourceId: "", method: "boleto" } },
  { value: "update_charge", label: "Editar cobranca", group: "Financeiro", target: true, example: { description: "Descricao atualizada" } },
  { value: "mark_charge_paid", label: "Marcar cobranca paga", group: "Financeiro", target: true, example: {} },
  { value: "create_crm_lead", label: "Criar lead", group: "CRM", example: { source: "outros", interest: "locacao", funnelStage: "novo" } },
  { value: "update_crm_lead", label: "Editar lead", group: "CRM", target: true, example: { funnelStage: "qualificado" } },
  { value: "create_crm_activity", label: "Criar atividade", group: "CRM", example: { leadId: "", kind: "nota", description: "Atividade automatica" } },
  { value: "schedule_visit", label: "Agendar visita", group: "CRM", example: { leadId: "", scheduledAt: "2026-07-10T14:00:00.000Z", description: "Visita agendada" } },
  { value: "create_rental_contract", label: "Criar contrato locacao", group: "Locacao", example: { propertyId: "", landlordClientId: "", tenantClientId: "", monthlyValue: 2500, dueDay: 10, startDate: "2026-07-01", endDate: "2027-07-01", durationMonths: 12, indexType: "ipca", adminFeePct: 10, lateFeePct: 2, lateInterestPctMonth: 1, status: "ativo" } },
  { value: "update_rental_contract", label: "Editar contrato locacao", group: "Locacao", target: true, example: { status: "em_renovacao" } },
  { value: "create_sale_listing", label: "Criar anuncio venda", group: "Vendas", example: { propertyId: "", askingPrice: 500000, status: "ativa", commissionPct: 6 } },
  { value: "update_sale_listing", label: "Editar anuncio venda", group: "Vendas", target: true, example: { status: "sob_proposta" } },
  { value: "create_sale_proposal", label: "Registrar proposta", group: "Vendas", example: { listingId: "", buyerClientId: "", brokerUserId: "", offeredPrice: 450000, status: "em_analise", history: [] } },
  { value: "move_sale_proposal", label: "Mover proposta", group: "Vendas", example: { proposalId: "", status: "contraproposta", note: "Movido por automacao" } },
  { value: "create_sale_contract", label: "Criar contrato venda", group: "Vendas", example: { listingId: "", buyerClientId: "", sellerClientId: "", finalPrice: 480000, status: "fechado" } },
  { value: "create_condo", label: "Criar condominio", group: "Condominio", example: { name: "Condominio", address: "Endereco", unitCount: 0, adminFeePct: 10 } },
  { value: "update_condo", label: "Editar condominio", group: "Condominio", target: true, example: { adminFeePct: 12 } },
  { value: "create_condo_unit", label: "Criar unidade", group: "Condominio", example: { condoId: "", label: "Apto 101", fractionPct: 0 } },
  { value: "generate_condo_fees", label: "Gerar taxas", group: "Condominio", example: { condoId: "", referenceMonth: "2026-07", dueDate: "2026-07-10", amount: 350 } },
  { value: "create_condo_expense", label: "Criar despesa", group: "Condominio", example: { condoId: "", referenceMonth: "2026-07", description: "Despesa", totalAmount: 1000, apportionment: "igual", status: "lancada" } },
  { value: "apportion_condo_expense", label: "Ratear despesa", group: "Condominio", target: true, example: {} },
  { value: "create_condo_meeting", label: "Criar assembleia", group: "Condominio", example: { condoId: "", date: "2026-07-10", kind: "ordinaria" } },
];

export const friendlyFieldLabels: Record<string, string> = {
  amount: "Valor",
  adminFeePct: "Taxa de administração (%)",
  apportionment: "Forma de rateio",
  askingPrice: "Preço pedido",
  brokerUserId: "Corretor responsável",
  buyerClientId: "Comprador",
  clientId: "Cliente",
  condoId: "Condomínio",
  conditions: "Condições",
  currentResidentClientId: "Morador atual",
  date: "Data",
  description: "Descrição",
  dueDate: "Vencimento",
  dueDay: "Dia de vencimento",
  email: "E-mail",
  endDate: "Fim do contrato",
  finalPrice: "Valor final",
  fractionPct: "Fração ideal (%)",
  funnelStage: "Etapa do funil",
  guarantorClientId: "Fiador",
  interest: "Interesse",
  kind: "Tipo",
  landlordClientId: "Proprietário",
  leadId: "Lead",
  listingId: "Anúncio",
  lostReason: "Motivo da perda",
  method: "Forma de cobrança",
  monthlyValue: "Valor mensal",
  name: "Nome",
  note: "Observação",
  offeredPrice: "Valor da proposta",
  ownerClientId: "Proprietário",
  paymentTerms: "Condições de pagamento",
  phone: "Telefone",
  propertyId: "Imóvel",
  proposalId: "Proposta",
  referenceMonth: "Mês de referência",
  scheduledAt: "Agendado para",
  sellerClientId: "Vendedor",
  source: "Origem",
  sourceId: "Parcela/taxa de origem",
  startDate: "Início do contrato",
  status: "Status",
  tenantClientId: "Inquilino",
  totalAmount: "Valor total",
  whatsapp: "WhatsApp",
};
