// Status string constants. Centraliza os valores mais repetidos no código
// para facilitar manutenção e evitar typos. Cada constante reflete o valor
// usado nos tipos de domínio (lib/types/domain.ts).

export const S = {
  PENDENTE: "pendente",
  PAGA: "paga",
  PAGO: "pago",
  VENCIDA: "vencida",
  VENCIDO: "vencido",
  CANCELADA: "cancelada",
  CANCELADO: "cancelado",
  FALHA: "falha",
  ATIVA: "ativa",
  VENDIDA: "vendida",
  ACTIVE: "active",
  PAUSED: "paused",
  VALIDADO: "validado",
  REJEITADO: "rejeitado",
  SOB_PROPOSTA: "sob_proposta",
  EM_ANDAMENTO: "em_andamento",
  FECHADO: "fechado",
  DISPONIVEL: "disponivel",
  ALUGADO: "alugado",
  EM_ANALISE: "em_analise",
  CONTRAPROPOSTA: "contraproposta",
  ACEITA: "aceita",
  RECUSADA: "recusada",
  EM_obra: "em_obra",
  INATIVO: "inativo",
  LOCACAO: "locacao",
  VENDA: "venda",
  AMBOS: "ambos",
  CONDOMINIO_ONLY: "condominio_only",
  ATIVO: "ativo",
  ENCERRADO: "encerrado",
  INADIMPLENTE: "inadimplente",
  EM_RENOVACAO: "em_renovacao",
  A_VENCER: "a_vencer",
  A_VENCER_CONDOMINIO: "a_vencer",
  LANCADA: "lancada",
  RATEADA: "rateada",
  ORDINARIA: "ordinaria",
  EXTRAORDINARIA: "extraordinaria",
  NOVO: "novo",
  QUALIFICADO: "qualificado",
  VISITA_AGENDADA: "visita_agendada",
  PROPOSTA: "proposta",
  FECHADO_GANHO: "fechado_ganho",
  FECHADO_PERDIDO: "fechado_perdido",
} as const;
